// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATOykh45dBdXnJ0UIBSvt4JAwUFqj1xnY',
    appId: '1:65936314048:web:c5a9612361ba94d1fee725',
    messagingSenderId: '65936314048',
    projectId: 'botomine-f7edb',
    authDomain: 'botomine-f7edb.firebaseapp.com',
    storageBucket: 'botomine-f7edb.appspot.com',
    measurementId: 'G-NEC5KWP23C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjHO3U6e10nJYR9bvWFKD3a1KuBx1ASEE',
    appId: '1:65936314048:android:86ccd26944741d84fee725',
    messagingSenderId: '65936314048',
    projectId: 'botomine-f7edb',
    storageBucket: 'botomine-f7edb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKrlPd2k3hAoD5RYbGQiri6By9kxpnhw4',
    appId: '1:65936314048:ios:7b697c4e909d84bdfee725',
    messagingSenderId: '65936314048',
    projectId: 'botomine-f7edb',
    storageBucket: 'botomine-f7edb.appspot.com',
    iosBundleId: 'com.example.botomine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKrlPd2k3hAoD5RYbGQiri6By9kxpnhw4',
    appId: '1:65936314048:ios:37638896f00f1348fee725',
    messagingSenderId: '65936314048',
    projectId: 'botomine-f7edb',
    storageBucket: 'botomine-f7edb.appspot.com',
    iosBundleId: 'com.example.botomine.RunnerTests',
  );
}
